### ISSUE TITLE
American Crime Story broken

### ISSUE THREAD

**Issue by bartolomesoriano** [pymedusa/medusa.github.io#320]
The automatic scene exceptions for American Crime Story make it so that episodes from season 3 cannot be found when searched.   As far as I understand, this show should not have any automatic scene exceptions any more.

**Comment by bdigital24** [comment]
Same problem here. Can't remove the hardcoded scene exceptions and it's causing Season 2 and 3 files to overwrite Season 1.

**Comment by medariox** [comment]
Which is the scene exception causing issues?

**Comment by bartolomesoriano** [comment]
The scene exceptions for season 1 and season 2

**Comment by medariox** [comment]
We only have 2 scene exceptions for season 1: https://github.com/pymedusa/medusa.github.io/blob/cc920712f1517a2003863f0a6a4024420ae8064c/scene_exceptions/scene_exceptions_tvdb.json#L2718-L2722

Not sure how these are causing issues?
You will need to post some debug logs, otherwise it will be tough to figure out what's going on.

**Comment by bartolomesoriano** [comment]
![Screenshot 2021-09-10 084444](https://user-images.githubusercontent.com/7786357/132855348-0a9fb09c-b376-416b-824a-4ffde0cbe341.png)

@medariox , if you look at the screenshot, the exception "American Crime Story" for Season 2 makes it so that when you try to download an episode for Season 3 (episode 1 is out now), Medusa thinks it is episode 1 of season 2, and overwrites that.

**Comment by p0psicles** [comment]
I think I have an idea of whats going on here.
There have been some bad entries a while ago. They got in through the tvdb scene exceptions file and have been removed.
The problem is, that scene exceptions are cached locally in a table. And there isn't a cache invalidation implemented here.
So the only option for now is to manually empty the `scene_exceptions` table in `main.db`. But then i'd recommend to not remove the custom exceptions.

I'll add a function to manage/searches, to empty the exceptions cache from ui.

You could open the main.db file with an sqlite3 editor. And run:
`delete from scene_exceptions where custom  = 0;`

And then restart.

**Comment by bartolomesoriano** [comment]
@p0psicles , thank you! That worked great.

**Comment by p0psicles** [comment]
From PR #9859 you'll be able to clean cache from UI.

**Comment by bdigital24** [comment]
Thanks all

**Comment by ddalben** [comment]
> I think I have an idea of whats going on here.
> There have been some bad entries a while ago. They got in through the tvdb scene exceptions file and have been removed.
> The problem is, that scene exceptions are cached locally in a table. And there isn't a cache invalidation implemented here.
> So the only option for now is to manually empty the `scene_exceptions` table in `main.db`. But then i'd recommend to not remove the custom exceptions.
> 
> I'll add a function to manage/searches, to empty the exceptions cache from ui.
> 
> You could open the main.db file with an sqlite3 editor. And run:
> `delete from scene_exceptions where custom = 0;`
> 
> And then restart.

Any way of doing this when medusa is in a container without an sqlite editor?
